title: Choropleth maker
port: 4000
host: 127.0.0.1

# Choose a key from data.yml
key: 'total'

scale:
  - num: 7
    color: '#8c2d04'
  - num: 6
    color: '#cc4c02'
  - num: 5
    color: '#ec7014'
  - num: 4
    color: '#fe9929'
  - num: 3
    color: '#fec44f'
  - num: 2
    color: '#fee391'
  - num: 1
    color: '#fff7bc'
  - num: 0
    color: '#ffffe5'
  - num: "null"
    color: 'transparent'